{"id": 3618136, "name": "kwotsin/tensorflow-xception", "isFork": false, "commits": 29, "branches": 2, "defaultBranch": "master", "releases": 1, "contributors": 2, "license": "MIT License", "watchers": 14, "stargazers": 186, "forks": 98, "size": 223343, "createdAt": "2017-05-09T11:59:18", "pushedAt": "2019-09-09T07:11:40", "updatedAt": "2020-12-14T07:33:12", "homepage": null, "mainLanguage": "Python", "totalIssues": 11, "openIssues": 6, "totalPullRequests": 4, "openPullRequests": 0, "blankLines": 198, "codeLines": 555, "commentLines": 317, "metrics": [{"language": "Python", "blankLines": 185, "codeLines": 519, "commentLines": 317}, {"language": "Markdown", "blankLines": 13, "codeLines": 36, "commentLines": 0}], "lastCommit": "2019-09-09T07:11:39", "lastCommitSHA": "c42ad8cab40733f9150711be3537243278612b22", "hasWiki": true, "isArchived": false, "languages": {}, "labels": [], "topics": [], "status": "patching_successfully", "repo_folder": "projects/kwotsin_tensorflow-xception"}